### PR TITLE
removed package.json

### PR DESCRIPTION
**Pull request by jideoyelayo1**

### CODE REVIEW

**Review by RCCG-JPDAG-TECH-OFFICE — CHANGES_REQUESTED** [review]
Why was this removed?

**Comment by jideoyelayo1** [comment]
It has not been implemeted

**Comment by jideoyelayo1** [comment]
Implementation is unnessecary since it does not make the use  better

**Review by RCCG-JPDAG-TECH-OFFICE — APPROVED** [review]
I see that is is not needed

**Review by JppUsers — APPROVED** [review]

**Review by trimmedjay — APPROVED** [review]
Approved

**Review by jayHasATrim — APPROVED** [review]

**Pull request merged**
